"""empty message

Revision ID: 21c43d21990c
Revises: 4ec93a1158b4
Create Date: 2024-10-07 22:04:48.826500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21c43d21990c'
down_revision = '4ec93a1158b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de__evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=1000), nullable=False))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de__evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
