"""empty message

Revision ID: 625edc35a601
Revises: 633e75ad78f1
Create Date: 2024-11-18 02:56:38.065424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625edc35a601'
down_revision = '633e75ad78f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=120), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('elemento', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventario')
    # ### end Alembic commands ###
