"""empty message

Revision ID: 633e75ad78f1
Revises: b3688e8504d5
Create Date: 2024-11-17 19:00:27.390042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633e75ad78f1'
down_revision = 'b3688e8504d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
