"""empty message

Revision ID: 7431fbaf08f7
Revises: b330991ce3b0
Create Date: 2024-10-08 02:55:39.459351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7431fbaf08f7'
down_revision = 'b330991ce3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de__evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido2', sa.String(length=120), nullable=False))
        batch_op.drop_column('url_imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de__evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_imagen', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('apellido2')

    # ### end Alembic commands ###
