"""empty message

Revision ID: 7d9d17943130
Revises: 625edc35a601
Create Date: 2024-11-18 18:25:36.059403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9d17943130'
down_revision = '625edc35a601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=999), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('participantes', sa.JSON(), nullable=False),
    sa.Column('realizado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('hora')

    op.drop_table('programacion')
    # ### end Alembic commands ###
