"""empty message

Revision ID: 81274940ab5a
Revises: bab9e0076896
Create Date: 2024-11-26 02:56:30.659162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81274940ab5a'
down_revision = 'bab9e0076896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacion', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacion', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.String(length=12),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
