"""empty message

Revision ID: a9a8354a533d
Revises: c6e2db8ae95f
Create Date: 2024-11-17 16:33:58.227538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a8354a533d'
down_revision = 'c6e2db8ae95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socio', schema=None) as batch_op:
        batch_op.drop_column('pago')

    # ### end Alembic commands ###
