"""empty message

Revision ID: acda50b48f11
Revises: 7d9d17943130
Create Date: 2024-11-19 13:59:18.214080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acda50b48f11'
down_revision = '7d9d17943130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacion', schema=None) as batch_op:
        batch_op.drop_column('hora')

    # ### end Alembic commands ###
