"""empty message

Revision ID: b330991ce3b0
Revises: 21c43d21990c
Create Date: 2024-10-08 02:55:03.942847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b330991ce3b0'
down_revision = '21c43d21990c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de__evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=1000), nullable=False))
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_de__evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
