"""empty message

Revision ID: be68e2c6003a
Revises: c6bc920e8767
Create Date: 2024-10-09 01:18:26.695828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be68e2c6003a'
down_revision = 'c6bc920e8767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participante')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participante',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('url_image', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_telefono', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre_contacto_emergencia', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_contacto_emergencia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asistencia_medica', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='participante_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='participante_pkey')
    )
    # ### end Alembic commands ###
