"""empty message

Revision ID: c6bc920e8767
Revises: 58ab563192a8
Create Date: 2024-10-09 01:12:17.114267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bc920e8767'
down_revision = '58ab563192a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participantes_de__eventos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participantes_de__eventos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_evento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_participante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apto_medico', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('asistencia', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id'], name='participantes_de__eventos_id_evento_fkey'),
    sa.ForeignKeyConstraint(['id_participante'], ['participante.id'], name='participantes_de__eventos_id_participante_fkey'),
    sa.PrimaryKeyConstraint('id', name='participantes_de__eventos_pkey')
    )
    # ### end Alembic commands ###
