"""empty message

Revision ID: c8d44552d015
Revises: 
Create Date: 2023-04-03 12:43:42.114592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d44552d015'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_de__evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('dificultad', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=False),
    sa.Column('url_imagen', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('url_image', sa.String(length=100), nullable=True),
    sa.Column('numero_telefono', sa.Integer(), nullable=True),
    sa.Column('nombre_contacto_emergencia', sa.String(length=100), nullable=True),
    sa.Column('numero_contacto_emergencia', sa.Integer(), nullable=True),
    sa.Column('asistencia_medica', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=80), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=120), nullable=False),
    sa.Column('id_monitor', sa.Integer(), nullable=False),
    sa.Column('cantidad_maxima_participantes', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('realizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_monitor'], ['monitor.id'], ),
    sa.ForeignKeyConstraint(['id_tipo'], ['tipo_de__evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participantes_de__eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=True),
    sa.Column('id_participante', sa.Integer(), nullable=True),
    sa.Column('apto_medico', sa.Boolean(), nullable=True),
    sa.Column('asistencia', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['id_participante'], ['participante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participantes_de__eventos')
    op.drop_table('evento')
    op.drop_table('participante')
    op.drop_table('monitor')
    op.drop_table('administradores')
    op.drop_table('user')
    op.drop_table('tipo_de__evento')
    # ### end Alembic commands ###
