"""empty message

Revision ID: da9a3f1195f4
Revises: acda50b48f11
Create Date: 2024-11-19 16:43:32.945422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9a3f1195f4'
down_revision = 'acda50b48f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administradores')
    op.drop_table('evento')
    op.drop_table('monitor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('monitor_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='monitor_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='monitor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('evento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('lugar', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('id_monitor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('realizado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('hora', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_monitor'], ['monitor.id'], name='evento_id_monitor_fkey'),
    sa.PrimaryKeyConstraint('id', name='evento_pkey')
    )
    op.create_table('administradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('rut', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('numero_telefono', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='administradores_pkey'),
    sa.UniqueConstraint('email', name='administradores_email_key'),
    sa.UniqueConstraint('rut', name='administradores_rut_key')
    )
    # ### end Alembic commands ###
